kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
  namespace: aap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
