apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  name: controller
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  create_preload_data: true
  route_tls_termination_mechanism: Edge
  init_container_extra_commands: |
    until getent hosts postgresql.ansible-automation-platform.svc.cluster.local
    do echo waiting for postgresql.ansible-automation-platform.svc.cluster.local
    sleep 2
    done
  garbage_collect_secrets: false
  ingress_type: Route
  loadbalancer_port: 80
  projects_use_existing_claim: _Yes_
  no_log: true
  init_container_image_version: latest
  image_pull_policy: IfNotPresent
  projects_storage_size: 8Gi
  auto_upgrade: true
  task_privileged: false
  projects_existing_claim: aac-data
  init_container_image: registry.access.redhat.com/ubi8/ubi
  projects_storage_access_mode: ReadWriteMany
  set_self_labels: true
  projects_persistence: true
  replicas: 1
  admin_user: admin
  loadbalancer_protocol: http
  nodeport_port: 30080
  postgres_configuration_secret: external-database
